### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by fernandezdiegoh** [pluralitybook/plurality#1021]
### Your public repo

https://github.com/fernandezdiegoh

### Your public branch

fernandezdiegoh

### Your email (optional)

fernandezdiego@gmail.com

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 10-Sep-24 17:07:52 UTC` by Gov4Git `dev`

The regusting user, @fernandezdiegoh, does not match the owner, @, of the provided Gov4Git public identity repo.
