### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by chatch** [pluralitybook/plurality#1022]
### Your public repo

https://github.com/chatch/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Have you contributed to the project yet?

**Comment by chatch** [comment]
i created a PR about a month ago: https://github.com/pluralitybook/plurality/pull/1023

not sure what this joining the community issue is about to be honest.  maybe it issue was auto-created when I created the PR?  i don't remember that.  so can ignore this one.   just wanted to submit the small fixes in that PR.

**Comment by GlenWeyl** [comment]
Approved

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 22-Oct-24 19:48:24 UTC` by Gov4Git `dev`

@chatch was added to the community.
