### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by Taiyou** [pluralitybook/plurality#1047]
### Your public repo

https://github.com/taiyou/gov4git-identity-public.git

### Your public branch

main

**Comment by Taiyou** [comment]
I am Hiro and work with Nishio-san and Suzuki-san.
I would like to join revisions of plurality book together.

**Comment by GlenWeyl** [comment]
Approved.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 16-Dec-24 21:30:27 UTC` by Gov4Git `dev`

@taiyou was added to the community.
