### ISSUE TITLE
Make figures in consistent, native format

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#12]
Currently, figures throughout the text are pulled from a variety of sources in a variety of formats and are not generated from natively available data.  This should be corrected.  We also need to ensure any copyright issues are resolved.

**Comment by ccerv1** [comment]
I have ideas for a standard we can use to store and annotate relevant source data in the repo. I will submit a PR to this effect!

**Comment by pluralitybook** [comment]
This issues has been addressed successfully but @ccerv1, but formatting has to be propagated throughout all the figures.

**Comment by GlenWeyl** [comment]
@ccerv1 is handling this, so I am closing it.
