### ISSUE TITLE
Passwords don't "establish" identity online. 

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#128]
Passwords are not a way to "establish" - or more precisely  create - an identity online. 

Passwords are a mechanism of authentication - that is a shared secret - shared between the service where the identifier was created/established and the entity that established it. 

In the process of account establishment (alternatively called, registration, enrollment, account creation) entities also articulate a password or shared secret that they can assert when returning to a given service to prove they are the entity that created an account (with an identifiers) and should control it for a given session/interaction.  

Passwords are a way to prove that one is the controler of a given identifier that they established in an enrollment process.

**Comment by pluralitybook** [comment]
Establish is deliberated used in two ways here: to create and to determine.  Passwords are used to determine an identity, but not to create.

**Comment by Identitywoman** [comment]
Well at least you are clear you are you aren't being clear with the language. I would expect more from a person who works for MSFT a technology company that is a leader in digital identity. 
Creating an account is a process that is very specific to digital identity.  Proving you own an account is a totally different thing. If we want to get this stuff right we have to use clear accurate language and not blur. 
After you have an account you can use a password to prove you are in fact the owner of the account. Using confusing jargon you are putting forward is not helpful in actually creating good digital identity systems when "registration / creation / enrollment / establishment" is confused or blurred with "authentication /  proving you are the person that created said account"
