### ISSUE TITLE
Add figure quantifying the Techlash

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#13]
My suggestion here would be using Google nGrams, but something more creative may be possible harnessing modern AI.  This belongs in the relevant techlash paragraph in the Introduction.

**Comment by Jordanu12** [comment]
![image](https://github.com/pluralitybook/plurality/assets/143449799/b92a980d-29f5-4634-86be-a76512542979)

**Comment by Jordanu12** [comment]
![image](https://github.com/pluralitybook/plurality/assets/143449799/51e5a9fb-55a0-480d-ba9c-d56482d4f59a)

**Comment by GlenWeyl** [comment]
@ccerv1 , for you to incorporate.
