### ISSUE TITLE
Reference to Sam being inspired by Aadhaar?

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#130]
https://github.com/pluralitybook/plurality/blob/2ee59fa976053b8eefcc09e17a157a2d873de597/contents/english/Identity.md?plain=1#L123

Is there a reference to where Sam says he was inspired by Aadhaar's "success"?

**Comment by GlenWeyl** [comment]
Fixed; see: https://www.reuters.com/technology/worldcoin-aims-set-up-global-id-network-akin-indias-aadhaar-2023-11-02/
