### ISSUE TITLE
Add figure on the decline of public sector R+D investment

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#14]
Ideally would also address the composition of this investment (information tech v. other areas).  This belongs in the Introduction in the paragraph on this topic.

**Comment by Jordanu12** [comment]
![image](https://github.com/pluralitybook/plurality/assets/143449799/025834cd-7d73-43f2-8347-5009ca3d2c8e)

**Comment by Jordanu12** [comment]
Can't find anyone who scores Federal R&D by technology typology.

**Comment by GlenWeyl** [comment]
@ccerv1 for you to incorporate.
