### ISSUE TITLE
GitCoin illustrations for Markets chapter

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#153]
The markets chapter starts with an example from GitCoin.  It would be good for folks from that community to edit and add illustrative images with appropriate permissions.

**Comment by owocki** [comment]
@pluralitybook @GlenWeyl  some options for what we could add here. open to your input tho!

an economic graph of a gitcoin grants round.  (each edge is a txn, each node is a user/grant)

<img width="1405" alt="Screenshot 2024-01-02 at 8 39 10 PM" src="https://github.com/pluralitybook/plurality/assets/513929/c8fcf187-02b0-4415-92b5-076c2daff3b4">

a ui widget that shows how when users input an amount their contributions get matched
![f4e0e409a7e97460bef805a439e656d2d6b07352](https://github.com/pluralitybook/plurality/assets/513929/e3d54880-3ada-41fa-b6fb-781cd8a58967)

some summary data from https://archive.grants.gitcoin.co/

some partner logos from https://impact.gitcoin.co/

an easy 1-2-3 state diagram showing how a gitcoin round works.  1. set up round 2. run crowdfund 3. distribute matching payout.

**Comment by GlenWeyl** [comment]
I think we probably mostly want to give a sense of user experience so I like the second (though in the printed version won't be dynamic) and then maybe something that is more like the grant explorer?

**Comment by owocki** [comment]
@GlenWeyl i started a draft PR => https://github.com/pluralitybook/plurality/pull/289

lets move the convo there. looking fwd to your feedback

**Comment by GlenWeyl** [comment]
Thank you, @owocki
