### ISSUE TITLE
Create a canonical diagram to illustrate the role of the various rights in the Freedom part

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#163]
A natural approach would be some sort of a hyper graph depiction showing what elements of the hypergraph are supported by each right: identity the notes, association the groups, commerce the quantification of the links, property and contract the collaborations and access the entry point.

**Comment by GlenWeyl** [comment]
Lillian is working on this.

**Comment by GlenWeyl** [comment]
Addressed by @lilian79511.
