### ISSUE TITLE
Issue credits to Derek

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#186]
Issue 5000 credits to @dworthen

**Comment by pluralitybook-dao** [comment]
Issued 5000 credits to member dworthen.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 16-Jan-24 19:31:34 UTC` by Gov4Git `dev`

Issued `5000` credits to member @dworthen.
