### ISSUE TITLE
Create Google ngrams chart for "artificial intelligence" in intro?

### ISSUE THREAD

**Issue by Fossj117** [pluralitybook/plurality#209]
I noticed that in the introduction that there are [several](https://github.com/pluralitybook/plurality/blob/9c19db18f42d85aa201954c8fea18feda2fc6a24/contents/english/02-introduction.md?plain=1#L119) [references](https://github.com/pluralitybook/plurality/blob/9c19db18f42d85aa201954c8fea18feda2fc6a24/contents/english/02-introduction.md?plain=1#L166) to a google N-grams chart for "artificial intelligence". Has this chart been generated? If not, I am happy to generate clean version of it and provide appropriate raw data / documentation as suggested in the [figs](https://github.com/pluralitybook/plurality/tree/main/figs) section. 

For reference, here is the raw version from Google that I would plan to replicate (with better labels & in the book's style):

<img width="1200" alt="Screen Shot 2023-11-15 at 5 07 20 PM" src="https://github.com/pluralitybook/plurality/assets/5392474/46f1d07a-6752-4d78-b5aa-eaeda5101d42">

If this sounds good, I will go ahead and generate a clean visual and open a PR. If there's anything else I should keep in mind, please let me know. Thanks.

**Comment by GlenWeyl** [comment]
Thank you for this!

**Comment by ccerv1** [comment]
@Fossj117 hey! just set up a pre-styled notebook for you to help with this if you are still able to.

**Comment by Fossj117** [comment]
@ccerv1 howdy sir! yes will do!
