### ISSUE TITLE
Add Microsoft XKCD cartoon to the "Workplace" chpater

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#213]

**Comment by gardenenigma** [comment]
Is [this](https://bonkersworld.net/organizational-charts) the cartoon being referred to?

It looks like it was originally created by "Manu Cornet", is under a creative commons license, and can be reused if [appropriate credit is provided](https://bonkersworld.net/about). I'm unsure if cropping the image to include only the MS org chart is appropriate as it would remove the artist signature - may need to contact the artist.

**Comment by GlenWeyl** [comment]
Yup this is the one...I think it would be appropriate to crop it and add attribution (saying it was adapted) or to use the whole thing as you think fits the space better.
