### ISSUE TITLE
Cite and improve statistics on time in meetings in "Workplace" chapter

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#214]

**Comment by michelezanini** [comment]
On the low value people get from meetings, these pieces have some good stats: 

https://www.nytimes.com/2023/04/07/business/office-meetings-time.html
https://www.theatlantic.com/family/archive/2022/11/why-meetings-are-terrible-happiness/672144/

**Comment by GlenWeyl** [comment]
Again, @GregCTWang feel free to incorporate and I'll share the credit.
