### ISSUE TITLE
Add citations on reduced productivity from remote work and causes to "Workplace" chapter

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#217]

**Comment by GlenWeyl** [comment]
@GregCTWang I believe you're on top of this.

**Comment by michelezanini** [comment]
Here are are few citations: 

A new (Nov. 2023) US study with software programmers finds that proximity to co-workers reduces short-term productivity, but boosts mentorship – which in turn increases human capital and earnings in subsequent years. [w31880.pdf](https://github.com/pluralitybook/plurality/files/14486802/w31880.pdf)

A study during the COVID-19 pandemic looked at data from more than 10,000 professionals at an Indian tech company who were working from home. It found that while people worked longer hours, their output slightly dropped, and productivity decreased by 8% to 19%. The study also explored why productivity changed. A key reason was the higher cost of communicating. People spent more time on organizing tasks and in meetings, but had less time for focused work. Employees also interacted with fewer colleagues and departments both inside and outside the company and had fewer individual meetings with their bosses. https://www.journals.uchicago.edu/doi/full/10.1086/721803


Study of 61,182 US Microsoft employees in the first half of 2020 found that moving to remote work made their teamwork networks less dynamic and more isolated, with fewer links between separate groups. There was also a shift from immediate to delayed communication. This situation might make it harder for employees to learn and share new information with each other:  https://www.nature.com/articles/s41562-021-01196-4

**Comment by GlenWeyl** [comment]
@GregCTWang if you want to go ahead and put in the citations I'll split credit between you two.

**Comment by GregCTWang** [comment]
@michelezanini Thanks for providing these resources. I also found the third piece of research and think it's a good fit. I will format them and include them in the next PR for the workspace chapter!

**Comment by GregCTWang** [comment]
@GlenWeyl PR created.
