### ISSUE TITLE
Improve evidence of efficacy of team-building activities and possibly picture of them to "Workplace" chapter

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#218]

**Comment by GregCTWang** [comment]
current evidences:

1. Properly cited
Klein, C., DiazGranados, D., Salas, E., Le, H., Burke, C. S., Lyons, R., & Goodwin, G. F. (2009, January 16). Does Team Building Work? Small Group Research, 40(2), 181–222. https://doi.org/10.1177/1046496408328821

Greenstone, M., Hornbeck, R., & Moretti, E. (2010, June). Identifying Agglomeration Spillovers: Evidence from Winners and Losers of Large Plant Openings. Journal of Political Economy, 118(3), 536–598. https://doi.org/10.1086/653714

2. Need conformation on the Barreto Bloom and Davis paper, will commit citation in APA format.
- a. Barrero, J. M., Bloom, N., & Davis, S. (2021, April). Why Working from Home Will Stick. https://doi.org/10.3386/w28731
- b. The Evolution of Working from Home. (n.d.). Stanford Institute for Economic Policy Research (SIEPR). https://siepr.stanford.edu/publications/working-paper/evolution-working-home

3. Need conformation on the Coinbase reference, will commit citation in APA format.

Huet. (2021, April 26). Basecamp Follows Coinbase In Banning Politics Talk at Work. Bloomberg. Retrieved March 1, 2024, from https://www.bloomberg.com/news/articles/2021-04-26/basecamp-follows-coinbase-in-banning-politics-talk-at-work

Kelly, J. (2020, October 1). Coinbase Won’t Allow Discussions Of Politics And Social Causes At Work—If Employees Don’t Like It, They’re Free To Leave. Forbes. Retrieved March 1, 2024, from https://www.forbes.com/sites/jackkelly/2020/10/01/coinbase-wont-allow-discussions-of-politics-and-social-causes-at-work-if-employees-dont-like-it-theyre-free-to-leave/?sh=58dcd8797459

**Comment by GregCTWang** [comment]
Additional evidence:

> Lunches among sufficiently realistic avatars, ones reflecting detailed facial expressions for example, may soon help bring the rich connections achieved in the office within the reach of remote teams.
- Brinkley, R. (2020, March 22). I ate a meal in virtual reality. Here’s what it tasted like. CNBC. https://www.cnbc.com/2020/03/21/virtual-reality-dining-explained.html

> Lunches among sufficiently realistic avatars, ones reflecting detailed facial expressions for example, may soon help bring the rich connections achieved in the office within the reach of remote teams.
- S. (2023, January 11). The Great Reevaluation: How Economic Headwinds and Cost of Living is Turning Americans into “Recession-Nomads.” https://www.prnewswire.com/news-releases/the-great-reevaluation-how-economic-headwinds-and-cost-of-living-is-turning-americans-into-recession-nomads-301718970.html

> there is increasingly strong evidence that real experiences of fear and trust can develop in sufficiently realistic simulated environments.
- Mühlberger, A., Bülthoff, H.H., Wiedemann, G., & Pauli, P. (2007). Virtual reality for the psychophysiological assessment of phobic fear: responses during virtual tunnel driving. Psychological assessment, 19 3, 340-6 .
- Poeschl, S., & Doering, N. (2014). Effects of simulation fidelity on user experience in virtual fear of public speaking training - an experimental study. Studies in health technology and informatics, 199, 66-70 .

**Comment by GregCTWang** [comment]
On activities:

- Klein, C., DiazGranados, D., Salas, E., Le, H., Burke, C. S., Lyons, R., & Goodwin, G. F. (2009, January 16). Does Team Building Work? Small Group Research, 40(2), 181–222. https://doi.org/10.1177/1046496408328821

> members who started as remote employees, miss the team-building benefits created by such activities
- Goff-Dupont, S. (2023, November 8). 18 high-impact virtual team building activities and games. Work Life by Atlassian. https://www.atlassian.com/blog/teamwork/virtual-team-building-activities-remote-teams
- Cai, K. (2022, February 2). Forget Meta’s Sleek Virtual Reality. Maybe The Metaverse Is Fun, Friendly, 8-Bit -- And Already Here. Forbes. https://www.forbes.com/sites/kenrickcai/2022/02/02/the-future-is-low-res/

**Comment by GregCTWang** [comment]
Perhaps we can also draw some activities from Stanford D.School related to creativity and design thinking, promoting collaboration, but not directly to digital tools or COVID-19.

**Comment by GregCTWang** [comment]
Updated citations following the citation style:

Barrero, Jose Maria, Nicholas Bloom, and Steven J. Davis. 2023. “The Evolution of Working from Home.” Working Paper No. 23-19, Stanford Institute for Economic Policy Research (SIEPR), Stanford, CA. https://siepr.stanford.edu/publications/working-paper/evolution-working-home.

Kelly, Jack. “Coinbase Won’t Allow Discussions Of Politics And Social Causes At Work—If Employees Don’t Like It, They’re Free To Leave.” Forbes, October 1, 2020. https://www.forbes.com/sites/jackkelly/2020/10/01/coinbase-wont-allow-discussions-of-politics-and-social-causes-at-work-if-employees-dont-like-it-theyre-free-to-leave/?sh=58dcd8797459.

Huet, Ellen. “Basecamp Follows Coinbase In Banning Politics Talk at Work.” Bloomberg.com, April 26, 2021. https://www.bloomberg.com/news/articles/2021-04-26/basecamp-follows-coinbase-in-banning-politics-talk-at-work.

Greenstone, Michael, Richard Hornbeck, and Enrico Moretti. “Identifying Agglomeration Spillovers: Evidence from Winners and Losers of Large Plant Openings.” Journal of Political Economy 118, no. 3 (June 2010): 536–98. https://doi.org/10.1086/653714.

Klein, Cameron, Deborah DiazGranados, Eduardo Salas, Huy Le, C. Shawn Burke, Rebecca Lyons, and Gerald F. Goodwin. “Does Team Building Work?” Small Group Research 40, no. 2 (January 16, 2009): 181–222. https://doi.org/10.1177/1046496408328821.
