### ISSUE TITLE
Add evidence of efficacy and intensity of VR experiences to "Workplace" chapter

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#219]

**Comment by GlenWeyl** [comment]
@GregCTWang I believe you are covering this.

**Comment by GregCTWang** [comment]
Added evidences:

[^GlobalCollab]: Umoren, Rachel, Dora J. Stadler, Stephen L. Gasior, Deema Al-Sheikhly, Barbara Truman, and Carolyn Lowe. “Global Collaboration and Team-Building through 3D Virtual Environments.” Innovations in Global Medical and Health Education 2014, no. 1 (November 1, 2014). https://doi.org/10.5339/igmhe.2014.1.

[^TeamCreativityInVirtual]: Alahuhta, Pekka, Emma Nordbäck, Anu Sivunen, and Teemu Surakka. “Fostering Team Creativity in Virtual Worlds.” Journal For Virtual Worlds Research 7, no. 3 (July 20, 2014). https://doi.org/10.4101/jvwr.v7i3.7062.

[^Game4TeamBuilding]: Ellis, Jason B., Kurt Luther, Katherine Bessiere, and Wendy A. Kellogg. “Games for Virtual Team Building.” Proceedings of the 7th ACM Conference on Designing Interactive Systems, February 25, 2008. https://doi.org/10.1145/1394445.1394477.

[^VirtualTeamWork]: Lukosch, Heide, Bas van Nuland, Theo van Ruijven, Linda van Veen, and Alexander Verbraeck. “Building a Virtual World for Team Work Improvement.” Frontiers in Gaming Simulation, 2014, 60–68. https://doi.org/10.1007/978-3-319-04954-0_8.

[^MRexample]: Lu, Lin, Honglin Wang, Pengran Liu, Rong Liu, Jiayao Zhang, Yi Xie, Songxiang Liu, et al. “Applications of Mixed Reality Technology in Orthopedics Surgery: A Pilot Study.” Frontiers in Bioengineering and Biotechnology 10 (February 22, 2022). https://doi.org/10.3389/fbioe.2022.740507.

Lu, Lin, Honglin Wang, Pengran Liu, Rong Liu, Jiayao Zhang, Yi Xie, Songxiang Liu, et al. “Applications of Mixed Reality Technology in Orthopedics Surgery: A Pilot Study.” Frontiers in Bioengineering and Biotechnology 10 (February 22, 2022). https://doi.org/10.3389/fbioe.2022.740507.
