### ISSUE TITLE
Improve sci-fi examples

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#22]
Footnote 23 in the introduction has a number of examples drawn from science fiction that could be more thoughtfully chosen.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 12-Jan-24 22:28:59 UTC` by Gov4Git `dev`

### Notice `6lp7zj`
Started managing this issue as Gov4Git concern `22` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 21:15:48 UTC` by Gov4Git `dev`

#### Notice `o36ibk`
This issue's __priority score__ is now `100.000000`.
The __cost of priority__ is `10000.000000`.
The __projected bounty__ is now `10000.000000`.

#### Notice `7ohyvp`
The set of eligible proposals claiming this issue is empty.

**Comment by remrys** [comment]
Some additional possibilities: 

- Marge Piercy: Woman on the Edge of Time (mindfully-chosen technology and societal design to support specific relationships between humans and each other, and between humans and the rest of nature
- Karl Schroeder: "Degrees of Freedom" in the Hieroglyph anthology (crowdsourced societal decision making) and Stealing Worlds (using virtual reality as a platform for experimental community-building)
- L.X. Beckett: Gamechanger (society recovering from climate change built around social credits)
- Ada Palmer: Terra Ignota series (people can self-select into available non-geographically-based governments)
- Monica Byrne: The Actual Star (technologically-enabled nomadic society with AI-enabled animal communication)
- Not actually science fiction, but a good non-fiction reference for this style of technologically-enabled interaction with nature is Karen Bakker's The Sounds of Life: How Digital Technology is bringing us closer to the Worlds of Animals and Plants
- Naomi Kritzer: "Better Living Through Algorithms" (what it might look like for AI to actually help people be happier)

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 19-Mar-24 18:31:04 UTC` by Gov4Git `dev`

#### Notice `cfd2zv`
This issue, managed as Gov4Git concern `22`, has been cancelled 🌂

The issue priority tally was `100.000000`.

Refunds issued:
- User @glenweyl was refunded `10000.000000` credits

Tally breakdown by user:
- User @glenweyl contributed `100.000000` votes
