### ISSUE TITLE
Issue with: "There is no native, non-proprietary protocol for identification"

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#235]
Found on this page near the bottom https://github.com/pluralitybook/plurality/blob/main/contents/english/04-00-rights-os-and-digital-freedom.md
"There is no native, non-proprietary protocol for identification"
This is a strong statement to be making when there are emerigng protocols that are non-proprietary developed by W3C and IETF to support just this - identification in the network.  Are they ubiquitous yet - no is that totally possible in the coming years yes. 

The next sentence also says this 
"no protocols for the ways we communicate and form groups online that allows free association,"
This is also soon to be not true - there is active work partly because of EU laws requiring advisarial interoperability work going on the MIMI (more instent messaging interoperability) at IETF in combination with the MLS (message layer security). 
There is also DIDComm that has been developed at DIF. 

It may be more accurate to say until now there haven't been these things and work is going on in both of these areas to create non-proprietary protocols and get adoption of them.

**Comment by GlenWeyl** [comment]
This all seems right and consistent with what we say in the associated full chapter in that section of the book.  Please feel free to propose an update.

**Comment by Identitywoman** [comment]
I made a pull request. 
https://github.com/pluralitybook/plurality/pull/357

**Comment by Identitywoman** [comment]
I will work on revising based on Glen's feedback.

**Comment by Identitywoman** [comment]
Made a pull request to address this. 
https://github.com/pluralitybook/plurality/pull/516

**Comment by Identitywoman** [comment]
Resolved with pull request acceptance.
