### ISSUE TITLE
slowness was not because of "centralization" 

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#242]
https://github.com/pluralitybook/plurality/blob/493c1aae9183eb51fa9840b43502b35d52211dc2/contents/english/04-01-identity-and-personhood.md?plain=1#L142

The "centrality" was not the problem. 
The "decentrality" was the problem. 
In Europe there was 27 countries each one had their own kind of "way" of managing its health system and its own way of issuing certificates - the EU worked very hard to stand up a system to support vaccine verification that would be interoperable. It managed to do it for this one type of credential. 
In the US the VCI system - was created by the SMART-Health Card folks and super decentralized - the big issue was how to manage the keys of the issuers - because there was so many different entities doing vaccination.  They sort of threw something together but it was a mess. Basically people just "trusted" those little paper cards. 

This issue of how do you figure out who to trust in a decentralized networked/system which basically every identity system is except the ultra centralized (India's Aadhaar, WorldCoin) - is the crux of the real world implementation problem.  We identified this issue in the good health pass collaborative work that I co-led and coming out of that was work to develop a directory or registries that is ongoing and has been picked up by UNDP - https://www.sparkblue.org/Regi-TRUST

**Comment by GlenWeyl** [comment]
Please feel free to suggest edits, I don't disagree with anything you're saying here.

**Comment by Identitywoman** [comment]
I think I addressed this in my edits that were already accepted.
