### ISSUE TITLE
History of Credit Card Network formation. 

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#248]
https://github.com/pluralitybook/plurality/blob/493c1aae9183eb51fa9840b43502b35d52211dc2/contents/english/04-03-commerce-and-trust.md?plain=1#L48C582-L48C582

Up until the 1980's credit cards still were "verified" in the field as it were. 
I remember my mom shopping using a credit card. 
They put the credit card in a device - put 3 layer carbon copy paper in it - ran the pressure over it. To imprint all the layers - my mom  then sign it. She would get the customer copy - then there was the merchant copy and the copy that was sent into the bank.  
There was also a book they could use to look up "invalid" numbers - that were no longer to be accepted. 

So it wasn't until the 1990s that credit card terminals to do real time verification of the numbers came into being. 

Interms of a source for how the Credit Card network Visa came about I recommend Birth of the Chaordic Age by Dee Hock - https://www.amazon.com/Birth-Chaordic-Age-Dee-Hock/dp/1576750744

You may find inspiration from some of the writing by and about him - 

https://ratical.org/many_worlds/ChaordicOrg.pdf

https://www.researchgate.net/publication/251108164_Associating_Dee_Hock_and_the_Creation_of_the_Organization

https://www.zampellagroup.com/wp-content/uploads/2016/07/Vision-of-Dee-Hock.pdf

https://www.researchgate.net/publication/264383828_The_Trillion-Dollar_Vision_of_Dee_Hock

https://globaltransforming.files.wordpress.com/2017/03/dee-hock-the_art_of_chaordic_leadership.pdf

https://www.chriscorrigan.com/parkinglot/wp-content/uploads/2015/01/Chaordic-Stepping-Stones-1.pdf

**Comment by GlenWeyl** [comment]
Yes my mother was actually an important exec at Veriphone in this transition.  Please feel free to update how we tell the story, but please don't add significant length as this is not a focal part of what we are trying to narrate.

**Comment by Identitywoman** [comment]
Addressed in Pull Request  314- https://github.com/pluralitybook/plurality/pull/314
