### ISSUE TITLE
ACH - 3 days - physical cheques. 

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#249]
https://github.com/pluralitybook/plurality/blob/493c1aae9183eb51fa9840b43502b35d52211dc2/contents/english/04-03-commerce-and-trust.md?plain=1#L52

ACH took 3 days because they were still physically shipping cheques around until like 2018. 
Now they settle it over night with photos of the cheques.

**Comment by GlenWeyl** [comment]
Feel free to correct.

**Comment by Identitywoman** [comment]
I worked to correct this and the whole history of the credit card and SWIFT. In Pull Request - https://github.com/pluralitybook/plurality/pull/314

**Comment by Identitywoman** [comment]
Thanks!
