### ISSUE TITLE
UPI - PayNow Interoperate

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#252]
https://github.com/pluralitybook/plurality/blob/493c1aae9183eb51fa9840b43502b35d52211dc2/contents/english/04-03-commerce-and-trust.md?plain=1#L69

UPI in India began in 2016. 

In 2023 India's UPI began interoperating with Singapore's PayNow system
https://indianexpress.com/article/explained/explained-economics/upi-singapore-paynow-integration-significance-8457391/

**Comment by GlenWeyl** [comment]
Great example!  please submit a PR to include.

**Comment by Identitywoman** [comment]
I submitted text and it was accepted closing issue.
