### ISSUE TITLE
"non-profits" are corporations. 

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#253]
https://github.com/pluralitybook/plurality/blob/493c1aae9183eb51fa9840b43502b35d52211dc2/contents/english/04-04-property-and-contract.md?plain=1#L31

Any organization that is formed with a corporate charter is a corporation - it is just a for-profit corporations and non-profit corporations and different flavors.

**Comment by GlenWeyl** [comment]
This was the intention, but feel free to clarify the language.

**Comment by Identitywoman** [comment]
Addressed this in pull request 313 - https://github.com/pluralitybook/plurality/pull/313
