### ISSUE TITLE
potentially referencing Weirdest People in the World, Assemblage Theory?

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#254]
https://github.com/pluralitybook/plurality/blob/493c1aae9183eb51fa9840b43502b35d52211dc2/contents/english/04-04-property-and-contract.md?plain=1#L78

This could be a good paragraph to talk about key aspects of the third section, "New Institutions, New Psychologies" of [Joseph Henrich's](https://en.wikipedia.org/wiki/Joseph_Henrich) book the Weirdest People in the World where the contemporary forms of organization that dominate now were experimentally innovated into being.  This also aligns with Assemblage Theory as a frame - there were many different people were coming together in new context - charter cities and meeting with strangers (non-kin) to shape and form new institutions - these experiments lead to the forms that were most useful/successful spreading (this is a population slection pressure).

**Comment by GlenWeyl** [comment]
I agree with the former comment as I see how it could be done briefly and support your making a PR on this...though I might put it all the way back on 04-00 or even 03-02 when we talk about the more general problems with the modern Weberian state as I think Henrich's points apply across these domains.  On Assemblage theory, as we corresponded about, I remain somewhat skeptic this can be done in a concise way that doesn't confuse the reader or add unnecessary and not very useful conceptual work, but I am open to looking at a PR.

**Comment by Identitywoman** [comment]
Created pull request - https://github.com/pluralitybook/plurality/pull/356
if the grammar is not perfect - sorry. 
hopefully grammar elves can address any fixes that are needed.
