### ISSUE TITLE
Richer formats then "conversation"

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#256]
https://github.com/pluralitybook/plurality/blob/493c1aae9183eb51fa9840b43502b35d52211dc2/contents/english/05-04-deliberation.md?plain=1#L25

There is a very rich set of deliberative methods that have been innovated in the last 50-60 years that do more then support "conversation". I often call these social technologies. 

Participedia https://participedia.net/
NCDD has a big collection of methods and a framework for understanding when to use what method - https://www.ncdd.org/streams.html

I know that digital tools present great promise - but I believe this is complementary promise to more broadly using working social technologies and augmenting them with appropriate digital technologies. I think this intersection could be a very fruitful one. 

This is a chart I worked on with Tom Atlee exploring his favorite - in person deliberation methods and the steps with potential online complements (which have of course advanced since then) 
https://identitywoman.net/wp-content/uploads/ExtremeTaoDemocracy.pdf

**Comment by GlenWeyl** [comment]
Agreed, and when added the earlier chapters in this part of the book plan to highlight some of these practices.  Once they are merged in, I'd encourage you to submit PRs if you think there are important practices not being covered.

**Comment by Identitywoman** [comment]
Great. Let me know when those sections are merged and I will read and raise some PRs if it makes sense to do so.

**Comment by GlenWeyl** [comment]
Early versions are already there, but you may want to wait as they are not organized in a very comprehensive way.  I'll let you know when they are.

**Comment by Identitywoman** [comment]
I went to read this page and didn't find any discussion of the highly performant actually in use in person deliberation and decision making methods.  If someone else isn't already doing this. May I add a paragraph about these?

**Comment by GlenWeyl** [comment]
Please.


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________
