### ISSUE TITLE
Neuroscience

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#27]
The discussion of neuroscience in the Plural World chapter is inadequately informed and missing parts.  This needs to be fixed.

**Comment by i2kmt** [comment]
Hey, I believe I could help with this. Could you please orientate me to what you would like to be added?

**Comment by pluralitybook** [comment]
@i2kmt, absolutely and thanks so much!  See the Plural World chapter.  There is a section on Neuroscience you should be able to find easily.  This section is very weak, compared to the sections on ecology, mathematics and physics.  I'd like to see it improved to both have the quality of these other sections (both in substance and citation support) and to parallel them in formatting.  Do you have the neuroscience background to do so?  Don't worry about writing tone matching too much...I can submit a PR to address any stylistic inconsistency.

**Comment by i2kmt** [comment]
Great! Well I am a medicine student, I have taken courses like neurophysiology and neuroanatomy. Besides that, I have just started reading and doing some brain modeling tutorials (there is a repository in my profile). I hope these make me qualified :) Is this okay?

**Comment by pluralitybook** [comment]
Absolutely!  Let’s see what you come up with.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 12-Jan-24 22:29:00 UTC` by Gov4Git `dev`

### Notice `7ntd3f`
Started managing this issue as Gov4Git concern `27` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.

**Comment by GlenWeyl** [comment]
We removed most scientific material so I am closing this issue.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Thursday, 22-Feb-24 16:07:44 UTC` by Gov4Git `dev`

#### Notice `gdafgc`
This issue, managed as Gov4Git proposal `27`, has been cancelled 🌂

The issue priority tally was `0.000000`.

Refunds issued:

Tally breakdown by user:
