### ISSUE TITLE
test: issue credits

### ISSUE THREAD

**Issue by petar** [pluralitybook/plurality#272]
issue 10 credits to @petar

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 17-Jan-24 13:09:55 UTC` by Gov4Git `dev`

Issued `10` credits to member @petar.
