### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by nishio** [pluralitybook/plurality#277]
### Your public repo

https://github.com/nishio/gov4git-identity-public.git

### Your public branch

main

### Your email (optional)

nishio.hirokazu@gmail.com

**Comment by GlenWeyl** [comment]
Approved

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 22-Jan-24 21:38:24 UTC` by Gov4Git `dev`

@nishio was added to the community.
