### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by Tofuswang** [pluralitybook/plurality#290]
### Your public repo

https://github.com/Tofuswang/gov4git-identity-public.git

### Your public branch

main

### Your email (optional)

terry.f.wang@gmail.com

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Friday, 02-Feb-24 14:43:10 UTC` by Gov4Git `dev`

The regusting user, @tofuswang, does not match the owner, @Tofuswang, of the provided Gov4Git public identity repo.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Saturday, 09-Mar-24 16:33:39 UTC` by Gov4Git `dev`

The regusting user, @tofuswang, does not match the owner, @Tofuswang, of the provided Gov4Git public identity repo.

**Comment by petar** [comment]
approve

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Saturday, 09-Mar-24 18:54:16 UTC` by Gov4Git `dev`

@tofuswang was added to the community.
