### ISSUE TITLE
Add discussion of OpenAI Democratic Inputs to AI grants to Deliberation and Voting chapters

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#291]
https://openai.com/blog/democratic-inputs-to-ai-grant-program-update

**Comment by jonas-kgomo** [comment]
I have added this discussion for the Deliberation part https://github.com/pluralitybook/plurality/pull/303

**Comment by jonas-kgomo** [comment]
Glen could you please keep this open for a few hours as Vanessa is adding the Voting chapter?

**Comment by GlenWeyl** [comment]
The issue doesn't need to be open for her to add; I'll give her credit for the PR regardless.


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________
