### ISSUE TITLE
I'd like to join this project's community, access the complete plurality book, and make contributions to the project.

### ISSUE THREAD

**Issue by Omoaholo** [pluralitybook/plurality#298]
### Your public repo

https://github.com/pluralitybook/plurality

### Your public branch

main

### Your email (optional)

omo@remakeafrica.com

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 05-Feb-24 22:44:21 UTC` by Gov4Git `dev`

The regusting user, @omoaholo, does not match the owner, @, of the provided Gov4Git public identity repo.
