### ISSUE TITLE
Add story about 1000 Cuts Journey or other empathetic immersive shared reality experience to start of that chapter.

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#299]

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 17:01:49 UTC` by Gov4Git `dev`

#### Notice `vkeqlm`
Started managing this issue as Gov4Git concern `299` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `hz3o2e`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `og7tl4`
The set of eligible proposals claiming this issue is empty.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 01-Mar-24 20:45:08 UTC` by Gov4Git `dev`

#### Notice `fweem6`
This issue's __priority score__ is now `422500.000000`.
The __cost of priority__ is `422500.000000`.
The __projected bounty__ is now `422500.000000`.

#### Notice `lfn7bw`
The set of eligible proposals claiming this issue is empty.

**Comment by lauerj** [comment]
If you compare the priority score, cost of priority and projected bounty for this issue #299 and the Nodes of Light issue #47 it seems like there is an error here. 
Nodes of Light has a score = sqrt(cost) and a bounty = 2*score whereas here score = cost = bounty.

**Comment by petar** [comment]
The two issues are managed by different mechanisms: gov4git:managed vs gov4git:pmp-v1. The former is an earlier implementation. The book will be using the latter going forward.

**Comment by GlenWeyl** [comment]
They used to be but are not anymore...the system seems not to have changed it over when I relabeled

**Comment by pluralitybook-dao** [comment]
Once labeled, the management mechanism for an issue does not change. Even
if you relabel. Your have to cancel the issue (which refunds everyone) and
open a new one with the new label.

**Comment by GregCTWang** [comment]
@GlenWeyl  "Becoming Homeless" example by Stanford: https://news.stanford.edu/2018/10/17/virtual-reality-can-help-make-people-empathetic/

**Comment by GlenWeyl** [comment]
This is a great one!  Are you up for trying to write this yourself or do you prefer I draft based on this?




___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Comment by lauerj** [comment]
@GlenWeyl just to clarify, what is the bounty on this issue? 422,500.0 seems high, or have I misunderstood the discussion on the change of G4G protocol (and 422,500.0 is the intended bountry)? Important to clarify before we submit PRs for voting.

**Comment by GregCTWang** [comment]
@GlenWeyl I can provide a draft. Would you like to include the examples of "1000 Cuts Journey" and "Becoming Homeless" before the current introduction section? If so, how extensive should these additions be?

**Comment by GlenWeyl** [comment]
@lauerj, I know this is a bit high, but 
1. I am trying to encourage people to use the bounty system
2. I have a lot of social capital in the system and want to get it out to others so am being generous
3. We're on a deadline and my bandwidth is limited
@GregCTWang  has already found a great idea for addressing this.  Perhaps you can can collaborate with him to write it up and share credit?

**Comment by GlenWeyl** [comment]
@GregCTWang the example should be of roughly the length of the illustrations at the beginning of other chapters in that Part of the book and in a similar style, about 1 page and in a style that is evocative, narrative and descriptive.

**Comment by lauerj** [comment]
@GregCTWang @GlenWeyl Thanks for the offer, I've been thinking about this Issue for a few days and in the 1-pager (~500 words) I would like to find a way to move beyond (just) '**evoking empathy**' to (actively) '**building bridges with difference**'.  So if the gaming concept would reward and incentivize bridging actions, that would be great! :) For example, the game could start at  as first-person player, but then move move to multi-player when appropriate level is reached. This would not take many words to convey. I think the Homelessness example as a narrative frame is great, and the 1000 Cut Journey would also work very well. In my own thinking (and I am prepared to abandon this), I really wanted to give regard to Indigeneous points of view and knowledge systems. My wife and I have spent a lot of time in Outback Australia, and what I can assure you is that 'we' do not have the same concept of 'objective reality' as Indigeneous Australiana, and what can be seen and felt and heard is an over-lapping but still v different set of (inter-subjective) 'facts', especially when it comes to ceremonial and ritual experience. So if we could insert ceremony and ritual (e.g. totems) in the game narrative in a concise and evocative way, that would be super! Let me know if you want to take first crack or should I?

**Comment by GlenWeyl** [comment]
If you look at the start of other chapters in the section, it can give you a sense, but yes this sounds good and I am sure you can do better than the other chapters.


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Comment by lauerj** [comment]
yes the other dramatic, evocative chapter intros are v good and are what inspired me.

**Comment by GlenWeyl** [comment]
Just to note that in this Part of the book (unlike Part 4) the intention is these are real stories of deployed technologies, rather than science fiction.


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Comment by GregCTWang** [comment]
@petar love your approach on this! Turning empathy into action through the 'game' idea and mechanisms, and especially your thoughts on incorporating Indigenous knowledge and ceremonies. You seem to have a solid structure for where this should go. I believe starting the draft would be best in your hands. I am happy to jump in and help flesh it out or refine it as we go along. Excited to see where you take this!

**Comment by lauerj** [comment]
@GlenWeyl ok thanks, that is an important clarification.

**Comment by lauerj** [comment]
@GregCTWang it sounds like we are circling back to your earlier suggestion: 
1. "I can provide a draft ... include the examples of "1000 Cuts Journey" and "Becoming Homeless" before the current introduction section". Te summarize:
2. It should be about 1-page in length (~500 words) 
3. It should show extended reality (XR) technologies can evoke empathy for difference. 
4. Iff there is scope to demonstrate building active bridges across difference then also add this (poli.is is an example of a technology for 'building bridges' but it is not XR-based).
Greg, thanks for the kind words about my approach, but based on the last feedback from Glen, my approach seems more tuned to Part 4 than Part 5. If you see the other Section 5 examples, they are 'dry and factual' in comparison with the imaginative narratives in Part 4... Based on this, if you want to draft for this Issue please go ahead! Or if you prefer me to take the lead, I am also happy to do so. Best, Jeremy

**Comment by lauerj** [comment]
@GregCTWang here is a short treatment for you to react to: 

<Proposed new chapter opening>
"Stand up and face the mirror" is the at-first innocent sounding, but gradually more-threatening, refrain that echoes through Courtney Cogburn's *1000 Cut Journey*.  Simple words that invite the visitor to this immersive-reality environment to experience life through the eyes, ears, and body of Michael Sterling, a black man.  Small moments of casual racism that build to a crescendo of hopelessness and induce a sense of helplessness.  Perception, or reality?  It depends on whose shoes you're standing in.  Some of us take off those shoes when we remove the VR headset, but for others there's no shoes you can buy that allow you to walk your way out. 

In *Becoming Homeless*, you look around your apartment to ecide which of your possessions to sell. You're losing your home, so it really doesn't matter anymore.  Then, from the moment of homelessness, your downward spiral accelerates: you lose your dignity, your physical security, your sense of self-worth and finally your health. No more hopes and dreams, thoughts and prayers can't help you now: you're in a daily grind that rips 20 to 30 years off your life expectancy. "Good luck!" "Work hard!" "I love you!" are now just words spoken long ago to another person you can hardly remember.

**Immersive shared reality technologies unlocks a new chapter in human interaction, leveraging cutting-edge virtual reality (VR), augmented reality (AR) and mixed reality (MR) systems. Unlike the deeply personal and sensorially rich exchanges of post-symbolic communication, shared immersive reality presents a broader canvas for human interaction, enabling people to engage in shared, multisensory experiences.** Not surprisingly, participants in activities where they can inhabit the perspectives of others multi-sensorially not only develop longer lasting empathy but are also more likely to engage in bridge-building actions [1]. 

**This chapter delves into the landscape of immersive technologies,...**

**^^existing text**

[1] Herrera F, Bailenson J, Weisz E, Ogle E, Zaki J. Building long-term empathy: A large-scale comparison of traditional and virtual reality perspective-taking. PLOS ONE 13(10): e0204494, 2018.

**Comment by lauerj** [comment]
If that concept^^ is something you're happy with, we can iterate it quickly to develop a PR.

**Comment by lauerj** [comment]
@GregCTWang here is a slightly more polished version at 261 words:

"Stand up and face the mirror" is the at-first innocent sounding, but gradually more-threatening, refrain that echoes through Courtney Cogburn's *1000 Cut Journey*. Simple words that invite the visitor to this immersive-reality environment to experience life through the eyes, ears, and body of Michael Sterling, a black man. Small moments of casual racism build to a crescendo of hopelessness and induce a sense of helplessness. Perception, or reality? It can depend on whose shoes you're standing in. Some of us take off those shoes when we remove the VR headset, but for others there's no shoes you can buy that allow you to walk your way out of this trap.

In *Becoming Homeless*, you look around your already bare apartment to decide which of your possessions to sell next.  You're losing your home, so it doesn't matter anymore, and you just choose something.  Then, from the moment of homelessness, the downward spiral rapidly accelerates: you lose your dignity, your physical security, and your health in quick succession.  No more hopes and dreams, thoughts and prayers can't help you now: you're in a daily grind that rips 20 to 30 years off your life expectancy faster than Jordan Belfort used to uncork a bottle of champagne. "Good luck!" "Work hard!" and - sadly - "I love you!" are now just words, spoken long ago, to a person you can hardly remember.

**Immersive shared reality technologies unlocks a new chapter in human interaction, leveraging cutting-edge virtual reality (VR), augmented reality (AR) and mixed reality (MR) systems. Unlike the deeply personal and sensorially rich exchanges of post-symbolic communication, shared immersive reality presents a broader canvas for human interaction, enabling people to engage in shared, multisensory experiences.** Not surprisingly, participants in activities where they can inhabit the perspectives of others multisensorially not only develop longer lasting empathy but are also more likely to engage in bridge-building actions [1].

**This chapter delves into the landscape of immersive technologies,...**

**^^existing text**

[1] Herrera F, Bailenson J, Weisz E, Ogle E, Zaki J. Building long-term empathy: A large-scale comparison of traditional and virtual reality perspective-taking. PLOS ONE 13(10): e0204494, 2018.

**Comment by GregCTWang** [comment]
I particularly enjoyed the storytelling aspect of the two examples, and how smoothly it transitions into the introduction of the technology. From my perspective, I believe adding more detail to the second part could further strengthen the discussion on 'immersive' technology. Additionally, I will incorporate citations. (sync from discord)

**Comment by GlenWeyl** [comment]
I absolutely love this kind of team work.  Thank you two.  For collaborative md work, I recommend HackMD over trading .md files this way.

**Comment by lauerj** [comment]
Great, I've registered for HackMD and created a link in case that is useful - @GregCTWang feel free to forge ahead on whatever platform you are using if that is easier for you!
https://hackmd.io/join/HkX0IaBa6

**Comment by GregCTWang** [comment]
@lauerj I've made revisions to the second section and would greatly appreciate any feedback you may have. Once we finalize the content, I'll ensure to properly use markdown for citing sources.

"Stand up and face the mirror" is the at-first innocent sounding, but gradually more-threatening, refrain that echoes through Courtney Cogburn's 1000 Cut Journey. Simple words that invite the visitor to this immersive-reality environment to experience life through the eyes, ears, and body of Michael Sterling, a black man. Small moments of casual racism build to a crescendo of hopelessness and induce a sense of helplessness. Perception, or reality? It can depend on whose shoes you're standing in. Some of us take off those shoes when we remove the VR headset, but for others there's no shoes you can buy that allow you to walk your way out of this trap.

In Becoming Homeless, you look around your already bare apartment to decide which of your possessions to sell next. You're losing your home, so it doesn't matter anymore, and you just choose something. Then, from the moment of homelessness, the downward spiral rapidly accelerates: you lose your dignity, your physical security, and your health in quick succession. No more hopes and dreams, thoughts and prayers can't help you now: you're in a daily grind that rips 20 to 30 years off your life expectancy faster than Jordan Belfort used to uncork a bottle of champagne. "Good luck!" "Work hard!" and - sadly - "I love you!" are now just words, spoken long ago, to a person you can hardly remember.

Immersive shared reality technologies, such as virtual reality (VR), augmented reality (AR), and mixed reality (MR), herald a new chapter in human interaction. These technologies, exemplified by Google's Project Glass publicly demonstrated in 2012, Microsoft's announcement of the enterprise-focused HoloLens in 2015, the consumer-directed Meta Quest headset unveiled in 2019, and the introduction of Apple Vision Pro in 2023, demonstrate the seamless integration of digital and physical realities. These technologies, alongside platforms like VIVERSE and Microsoft Mesh, enrich our interaction with virtual environments through gestures like tap, press, pinch, drag & drop, and grab, mirroring natural human actions. By enabling diverse activities, from gaming in Minecraft to remote assistance, real-time collaboration, and immersive training across sectors such as manufacturing and healthcare, these technologies foster a more profound empathy and a stronger inclination towards societal contribution.

The intuitiveness of these interactions relies on holographic interfaces that align with human cognition, thus guiding users' intentions and gestures through the interfaces' affordances within virtual spaces. This creates new dimensions of cognition for users, fostering deeper empathy and societal engagement. Intuitive interactions encourage designers and developers to create applications that mirror our interactions with the physical world. As these technologies facilitate everything from gaming to remote collaboration and training across industries, they herald a future where the digital and physical realms enrich each other, nurturing a more connected and empathetically engaged society.

--
Herrera F, Bailenson J, Weisz E, Ogle E, Zaki J. Building long-term empathy: A large-scale comparison of traditional and virtual reality perspective-taking. PLOS ONE 13(10): e0204494, 2018.

“1,000 Cut Journey  | Cogburn Research Group,” n.d. https://cogburnresearchgroup.socialwork.columbia.edu/research-projects/1000-cut-journey.

Stanford News. “Virtual Reality Can Help Make People More Empathetic | Stanford News,” October 15, 2018. https://news.stanford.edu/2018/10/17/virtual-reality-can-help-make-people-empathetic/.

**Comment by lauerj** [comment]
_@GregCTWang Your additions are great, and they really spell out the details more concretely! <3 I've got nothing to add or change in the last two paragraphs. Thanks also for adding the references for 1000 Cut Journey and Becoming Homeless. I've made a few more tweaks to the first two paragraphs, pasting them in here, to cut unecessary words, implicate the reader more personally and play with the concept of 'fluid self' which is at the heart of XR:_

"Stand up and face the mirror", the at-first innocent but gradually more-threatening refrain, echoes through Courtney Cogburn's *1000 Cut Journey*. Simple words that invite the visitor to this immersive-reality environment to experience life through the eyes, ears, and body of Michael Sterling, a black man.  Small moments of casual racism build to a crescendo of hopelessness and induce a pervasive sense of helplessness.  Perception, or reality?  It depends on whose shoes you're standing in.  Some may kick off their shoes the moment they remove the VR headset, but for Michael Sterling, there's nothing he (or now you) can do to erase the footprints of direct experience.  

In *Becoming Homeless*, you look around your already bare apartment to decide which possessions to sell next.  You're losing your home, so it doesn't matter anymore, and you just choose something.  Then, from the moment of actual homelessness, the downward spiral accelerates: you lose your dignity, your physical security, and your health in quick succession.  No more hopes and dreams, thoughts and prayers can't help you now: your new daily grind rips 25 years off your life expectancy faster than Jordan Belfort could uncork a bottle of champagne. "Good luck!" "Work hard!" and - sadly - "I love you!" are now just words you might have heard long ago, spoken to a person you can hardly remember.

**Comment by GregCTWang** [comment]
Wonderful! I will submit a PR based on our collaborative outcome. Thank you for laying the groundwork and flow for this introduction!

**Comment by lauerj** [comment]
@GregCTWang Amazing! Really happy to collaborate with you on this and have learned a lot in doing so!

**Comment by GregCTWang** [comment]
@GlenWeyl PR #454 submitted

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Wednesday, 06-Mar-24 17:13:52 UTC` by Gov4Git `dev`

#### Notice `6gxppn`
This issue, managed as Gov4Git concern `299`, has been cancelled 🌂

The issue priority tally was `650.000000`.

Refunds issued:
- User @glenweyl was refunded `422500.000000` credits

Tally breakdown by user:
- User @glenweyl contributed `650.000000` votes
