### ISSUE TITLE
WorldCoin has almost no adoption - Aadhaar is not a panacea

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#320]
https://github.com/pluralitybook/plurality/blob/b1750f57a09c99b491762f1a098d4faa004252eb/contents/english/04-01-identity-and-personhood.md?plain=1#L129

"Many have remarked that these systems have achieved some of the most impressive mixes of scale, inclusion of marginalized communities and security of any identity scheme in the world. "

So this paragraph is bluring assertions made about Aadhaar - with assertions made about WorldCoin. 

WorldCoin has almost no adoption. 

Aadhaar was deployed by the largest democracy in the world.

So it is not right to compare or even mention them in the same frame.  Sam is trying hard to get adoption - and I have heard through the grape vine he is talking to states or those close to states. I think a private company doing this with hashed iris' on blockchains is totally different then a global south superpower figuring out how to "catch up" to global north norms is what the story is. 

It is also worth noting to at least those digging in deep enough to find the "Issues" raised 
There has been intensive public messaging by the Indian state and proponents of Aadhaar about its goodness and amazingness in world press all while within India decent about the system is actively suppressed - with criminal investigations started against those who detract publicly in the media (low and behold public critique stopped in the media) - I know this happened because I met the people who myself who were on the receiving end of this. 

The UIDAI was basically extra-legal for the first 6 years of its existence - meaning it had NO basis in law. It was retroactively given its legal recognition by the state. 

I also think it is unfair to not reference western liberal democratic systems that are basically totally inclusive and have been for a very long time. When people are born in Europe and North America they get birth certificates and national social insurance or national ID numbers and the state manages to track them in limited ways throughout their lives. 

Some of the detractors to Aadhaar in India were very clear that the Indian state has no such power under its constitution to do what it did and that it should have instead invested in the local offices that do birth registration - so they could be capable of doing their job well and it was at this level of government and governance that this population registration should happen.

**Comment by GlenWeyl** [comment]
I don't disagree with any of this, nor do I think the text does.  if you want to try a rewrite without adding length, go for it.

**Comment by GlenWeyl** [comment]
One slight possible disagreement is comparing Europe to India.  India has about double the population of all of Europe and has living standards an order of magnitude lower.  There are many issues with India Stack, but I think belittling what it accomplished is a mistake.

**Comment by Identitywoman** [comment]
I don't know that I was trying to compare anything. 

I don't know that in the body of the Plurality text I belittled anything. I just think saying India has the most inclusive system is not complete context other countries have that too - they simply achieved it in a different way. 

Saying in this forum (issues in the deep in github about the text). That Aadhaar is more complex then the "happy story" that folks who are proponents have ensured is what is said in the public square. 

I literally spoke to several people and organizations who raised legitimate real criticisms of Aadhaar in the public sphere in India and found themselves being investigated in criminal complaints. I would name them here but that isn't right. I am happy to introduce you if you want to hear what happened to them for yourself.  It did what it was intended to do - suppress legitimate good faith critiques and issue raising in the public sphere in the largest democracy in the world. 

Here are some resources for those who would like to explore aadhaar and some of the issues around it and that were raised. 
 [my research Key Differences Between the U.S. Social Security System and India’s Aadhaar System (Kaliya Young)](https://www.newamerica.org/fellows/reports/anthology-working-papers-new-americas-us-india-fellows/key-differences-between-the-us-social-security-system-and-indias-aadhaar-system-kaliya-young/). 

[Dissent On Aadhaar: Big Data Meets Big Brother](https://www.amazon.com/Dissent-Aadhaar-Data-Meets-Brother/dp/9352875427/) Edited by Reetika Khera
