### ISSUE TITLE
Footnotes and citation in The Lost Dao

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#35]
The Lost Dao chapter needs footnotes and citations throughout, roughly 1-2 per paragraph. If the process turns up incorrect claims in the text, please submit an issue and tag @pluralitybook.

**Comment by GregCTWang** [comment]
Added sources:

Stafford Beer business cybernetics: 
Dickson, Paul. “Sputnik’s Impact on America.” NOVA | PBS, November 6, 2007. https://www.pbs.org/wgbh/nova/article/sputnik-impact-on-america/.

Deming’s 14 Points:
UTHSC. “Deming’s 14 Points,” May 26, 2022. https://www.uthsc.edu/its/business-productivity-solutions/lean-uthsc/deming.php.

Sputnik impact on US technology policy:
Dickson, Paul. “Sputnik’s Impact on America.” NOVA | PBS, November 6, 2007. https://www.pbs.org/wgbh/nova/article/sputnik-impact-on-america/.

Man-Computer Symbiosis: 
J. C. R. Licklider. “Man-Computer Symbiosis,” March 1960. https://groups.csail.mit.edu/medg/people/psz/Licklider.html.

Douglas Engelbart Augmentation Research Center: 
“Douglas Engelbart Issues ‘Augmenting Human Intellect: A Conceptual Framework’ :  History of Information,” October 1962. https://www.historyofinformation.com/detail.php?id=801.

The Computer as a Communication Device: 
Ritchie, Hannah, Edouard Mathieu, Max Roser, and Esteban Ortiz-Ospina. “Internet.” Our World in Data, April 13, 2023. https://ourworldindata.org/internet.

The mother of all demos:
Engelbart, Christina. “Firsts: The Demo - Doug Engelbart Institute.” Doug Engelbart Institute, n.d. https://dougengelbart.org/content/view/209/.
