### ISSUE TITLE
Issuing credits to Ryan

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#361]
Issue 120,192 credits to @rmcgranaghan.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 28-Feb-24 17:40:42 UTC` by Gov4Git `dev`

Your directive cannot be parsed.
