### ISSUE TITLE
Issue credits to Matt.

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#362]
Issue 120,192 credits to @anoanoano.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 28-Feb-24 17:40:41 UTC` by Gov4Git `dev`

Your directive cannot be parsed.
