### ISSUE TITLE
Do we need a section on principal-agency?

### ISSUE THREAD

**Issue by lauerj** [pluralitybook/plurality#378]
I am contributing to the health chapter 06-03, which should soon be merged. One issue Glen and I talked about at length is How much health-specific theoretical background does the Plurality book need? The initial draft of 06-03 that I wrote had a lot of health-specific background, most of which has now been jettisoned by mutual agreement (partly for constraints of time, partly for the specific focus of the book, and partly because it was important to have a concrete and evocative health chapter in its own right).

I think there's room to add more background material about health, but recently my thoughts have centered around the more specific and framing of **Principal-Agency** as a generic mechanism for organizing collaboration and collective action. A chapter on this class of mechanisms could be added in Section 5 alongside the chapters on the various mechanisms for Voting, Deliberation, Markets, and Administration, which it seems to belong with, moreover. 

The fundamental reason for principal agency is asymmetric knowledge, and one of the canonical examples is the doctor-patient relationship. Doctors are only asmall part, however, of the health system, and the existence of doctors alone would not be enough to justify adding a section on principal-agency. However, principal-agency arising from the healer-patient relationship functions as a kind of kernel that determines the cast of the whole health system, running through it from top to bottom, as we saw at times to our detriment during COVID. 

As a major part of human activity (10% of gross world output) and a major determinant of human welfare, I think the health system and its foundations deserve more theoretical attention in a book on Plurality. Principal-agency is moreover a generic principle that cuts across the fields of education, law, and divinity (the 3 classic professions) but emerges in its proto-form in family relationships (e.g. the age of majority for marriage and sexual relations, then by extension for public functions such as driving, working, and voting). While not a fixed number, majority is considered the threshold for emancipation from parental authority and the emergence of the person as a fully fledged person without need of principal-agency save in specific domains of activity.

Principal-agency as a social organizing principle seems less relevant as general education levels increase, and so the specific authorities of the doctor, lawyer, and cleric are being increasingly called into question. The health system as a major part of all societies still functions, however, as a kind of 'last bastion' of paternalism, and it therefore deserves more attention and critique. What would plural mechanisms to replace principal-agency in health look like? Online communities of practice, for example. LLM medical avatars as another. Let's brainstorm a bit and tackle this in a future iteration!

**Comment by GlenWeyl** [comment]
I am open to some material on this somewhere in the book...but I don't think it belongs as a point along the spectrum of chapter 5 that defines the entries there.

**Comment by lauerj** [comment]
Fair enough! In service of continuing the thinking, it seems the basic plural mechanism that addresses the same defect principal-agency tries to remedy (which is anyway often merely a workaround for uncertainty or for just plain ignorance) is **pooling** in order to surface an estimate of the population mean (or mode). Communities of practice and LLMs are both essentially pooling or averaging mechanisms, and as such they are compression algorithms (to extract summary statistics). The use of insurance (not just health insurance but more broadly in society) is probably one of the more prevalent applications of public-goods logic where exceptionally the utility and marketability of the PG are intuitively obvious even to pre-literate and pre-numerate societies. Insurance is a almost never undersupplied (though it may frequently be sub-optimal in welfare terms).

**Comment by GlenWeyl** [comment]
I this framing, I'd push you to think about intervention on chapter 05-07 on markets.


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Comment by lauerj** [comment]
Ok that is v interesting, will ponder! Thanks!

**Comment by lauerj** [comment]
I will leave this open in case there are further thoughts from others.

**Comment by lauerj** [comment]
I will leave this issue open for now in case others wish to add any further thoughts.

**Comment by lauerj** [comment]
Closing this issue for now.
