### ISSUE TITLE
Funding the matching pool

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#388]
Give 2000000 credits to matching fund.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Thursday, 29-Feb-24 21:23:07 UTC` by Gov4Git `dev`

Transferred `2e+06` credits from member @glenweyl to the matching fund.
