### ISSUE TITLE
Paragraph about deliberation coming. 

### ISSUE THREAD

**Issue by Identitywoman** [pluralitybook/plurality#398]
https://github.com/pluralitybook/plurality/blob/42ffd31c23facce9e1af8456c9f38cd49ebf7de9/contents/english/05-04-augmented-deliberation.md?plain=1#L46

I'm working on adding a paragraph here. I hope t have it in before I fly out of the country on Sunday. 
Referencing this issue where I first raised them. 
https://github.com/pluralitybook/plurality/issues/256

**Comment by GlenWeyl** [comment]
I understand, but please do review the first two chapters of this part of the book and ensure you put it in the appropriate place in the flow.
