### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by Tomatcree01** [pluralitybook/plurality#410]
### Your public repo

https://github.com/tomatcree01/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Hi, have you contributed yet?  Are you on Discord?

**Comment by georgepor** [comment]
@GlenWeyl, how can I find the Plurality server on Discord?

**Comment by GlenWeyl** [comment]
https://discord.gg/bM3ZYA6b is discord.

**Comment by Tomatcree01** [comment]
> Hi, have you contributed yet? Are you on Discord?

Sorry for the late response,
I joined the discord but I haven't contributed yet. Im trying to familiarize myself currently. I want to test some of the gov4git app to see if I can break something when I get some time to.

**Comment by GlenWeyl** [comment]
Approved.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 18-Mar-24 18:56:03 UTC` by Gov4Git `dev`

@tomatcree01 was added to the community.
