### ISSUE TITLE
Add chart on internet and PC adoption to The Lost Dao chapter

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#42]
The chapter discusses the rise of the PC and internet, which could use a quantitative illustration drawing on data like https://www.statista.com/statistics/214641/household-adoption-rate-of-computer-in-the-us-since-1997.  @ccerv1.

**Comment by ccerv1** [comment]
How's this?
It's a fork of this [one](https://ourworldindata.org/internet)
![share_online](https://github.com/pluralitybook/plurality/assets/42869436/2c307f3c-40b3-45a6-9c86-773d142364ba)

**Comment by GlenWeyl** [comment]
Perfect thank you!
