### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by JunsolKim** [pluralitybook/plurality#431]
### Your public repo

https://github.com/junsolkim/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Hi, have you contributed yet or what is your interest in the project?

**Comment by JunsolKim** [comment]
I am PhD student working with James Evans at the University of Chicago. James and I have published together in this area, and we are both diving in to see if we can be helpful, especially on Chapter 3. Let me know if you have any questions.

**Comment by GlenWeyl** [comment]
Approved.

**Comment by GlenWeyl** [comment]
@JunsolKim Great!  Joining here will allow you to get credit but you can submit a PR regardless.  Issues posted are things we could especially use help on.  Gov4Git will give you a guide to their priority, but they are also listed as comments on issues.

**Comment by GlenWeyl** [comment]
Consider joining us on Discord: https://discord.gg/YuPpGMwN

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 06-Mar-24 01:58:51 UTC` by Gov4Git `dev`

@junsolkim was added to the community.
