### ISSUE TITLE
Credits to Greg

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#442]
Issue 15000 credits to @GregCTWang.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 05-Mar-24 09:10:32 UTC` by Gov4Git `dev`

Issued `15000` credits to member @gregctwang.
