### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by tsuzumik** [pluralitybook/plurality#444]
### Your public repo

https://github.com/tsuzumik/gov4git-identity-public.git

### Your public branch

main

**Comment by tsuzumik** [comment]
My contribution are still very few yet. I added a few index word : https://docs.google.com/spreadsheets/d/1gmyjFbErt_CW8-qLKChSpciLlCDGUhLriYFov0HO3qA/edit#gid=0
I will find something useful for Japanese version.

**Comment by GlenWeyl** [comment]
Approved

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Tuesday, 05-Mar-24 15:35:15 UTC` by Gov4Git `dev`

@tsuzumik was added to the community.
