### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by dedededalus** [pluralitybook/plurality#448]
### Your public repo

https://github.com/dedededalus/gov4git-identity-public.git

### Your public branch

main

**Comment by dedededalus** [comment]
Hello, nice to meet you.
I am someone who is assisting in the Japanese Plurality translation project, in a small way.

I have also been involved in creating the index.
https://docs.google.com/spreadsheets/d/1gmyjFbErt_CW8-qLKChSpciLlCDGUhLriYFov0HO3qA/edit#gid=0

I am interested in learning more about Plurality. Thank you very much.

**Comment by GlenWeyl** [comment]
Approved!  Looking forward to your contribution.  Please consider joining us on Discord: https://discord.gg/YuPpGMwN

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 06-Mar-24 01:58:46 UTC` by Gov4Git `dev`

@dedededalus was added to the community.
