### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by jamesallenevans** [pluralitybook/plurality#449]
### Your public repo

https://github.com/jamesallenevans/gov4git-identity-public.git

### Your public branch

main

**Comment by jamesallenevans** [comment]
> ### Your public repo
> https://github.com/jamesallenevans/gov4git-identity-public.git
> 
> ### Your public branch
> main

Sorry it took me so long to get in here--last weeks of the quarter. But that's over now! Happy to dive in the next few days and help with existing sections (if helpful). In invited Junsol Kim, one of my star students, to dive in and work on this as well.

**Comment by GlenWeyl** [comment]
Approved.

**Comment by GlenWeyl** [comment]
Consider joining us on Discord: https://discord.gg/YuPpGMwN

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 06-Mar-24 01:58:44 UTC` by Gov4Git `dev`

@jamesallenevans was added to the community.
