### ISSUE TITLE
Issuing credits to Geordan

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#450]
Issue 250000 credits to @GeordanShannon

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 06-Mar-24 01:58:54 UTC` by Gov4Git `dev`

Issued `250000` credits to member @geordanshannon.
