### ISSUE TITLE
Quantitatively illustrate impact of OSS

### ISSUE THREAD

**Issue by pluralitybook** [pluralitybook/plurality#46]
Add a chart to the Nodes of Light section of The Lost Dao chapter illustrating the impact of OSS. @ccerv1

**Comment by ccerv1** [comment]
I think it would be cool to show a network graph either of dependencies among or contributors to different OSS projects. Something along the lines of [this](https://woc-hack.github.io/collab-graph/projects/)? What do you think?

[Here](https://arxiv.org/pdf/2103.12168.pdf) is the paper this graph comes from.

![image](https://github.com/pluralitybook/plurality/assets/42869436/029c8c43-f50c-419a-889f-e074e9df528b)

**Comment by GlenWeyl** [comment]
Sorry I never responded here.  This is a beautiful illustration, but I guess the question is of what in that context?  What I really want to convey to people is that their lives depend on this stuff...

**Comment by ccerv1** [comment]
Added this exhibit in my latest PR:
https://github.com/ccerv1/plurality/tree/main/figs/data/oss_impact
