### ISSUE TITLE
Funding matching pool

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#462]
Give 1000000 credits to the matching fund.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 06-Mar-24 20:00:41 UTC` by Gov4Git `dev`

Your directive cannot be parsed.
