### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by patcon** [pluralitybook/plurality#466]
### Your public repo

https://github.com/patcon/gov4git-identity-public.git

### Your public branch

main

**Comment by patcon** [comment]
My intro message on discord: https://discord.com/channels/1133444567031627846/1142734351881220116/1215418619497025667

(I can aim to make a PR first if required, but will admit I'm also very curious to see how gov4git works, even before I make a PR 😁 )

**Comment by GlenWeyl** [comment]
You can't really do anything meaningful on Gov4Git until you have tokens and that requires a PR.  But you can download the app.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Friday, 08-Mar-24 13:57:23 UTC` by Gov4Git `dev`

@patcon was added to the community.
