### ISSUE TITLE
I'd like to join this project's community (I've been contributing for a while without knowing I had to join this way).

### ISSUE THREAD

**Issue by Omoaholo** [pluralitybook/plurality#474]
### Your public repo

https://github.com/pluralitybook/plurality

### Your public branch

main

### Your email (optional)

omo@remakeafrica.com

**Comment by Omoaholo** [comment]
Thanks to Glen for the guidance.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Saturday, 09-Mar-24 16:18:22 UTC` by Gov4Git `dev`

The regusting user, @omoaholo, does not match the owner, @, of the provided Gov4Git public identity repo.
