### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by bioregionaltracy** [pluralitybook/plurality#537]
### Your public repo

https://github.com/bioregionaltracy/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Have you contributed to this project?

**Comment by bioregionaltracy** [comment]
Yes.  I supported Kaliya (Identity Woman) on the Deliberation section.

Tracy Kunkler
Co-Director
https://circleforward.us/ 
828-242-8199
Or schedule time:
https://calendly.com/tracykunkler 

￼

**Comment by GlenWeyl** [comment]
Approved.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 13-Mar-24 16:26:16 UTC` by Gov4Git `dev`

@bioregionaltracy was added to the community.
