### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by Jordanu12** [pluralitybook/plurality#539]
### Your public repo

https://github.com/jordanu12/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Approved

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 13-Mar-24 11:49:04 UTC` by Gov4Git `dev`

@jordanu12 was added to the community.
