### ISSUE TITLE
Issuing credits to Jordan

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#546]
Issue 80000 credits to @Jordanu12.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 13-Mar-24 12:00:36 UTC` by Gov4Git `dev`

Issued `80000` credits to member @jordanu12.
