### ISSUE TITLE
Issue credits to Tracy

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#551]
Issue 5000 credits to @bioregionaltracy.

**Comment by bioregionaltracy** [comment]
Thank you!

Tracy Kunkler
Co-Director
https://circleforward.us/ 
828-242-8199
Or schedule time:
https://calendly.com/tracykunkler 

￼

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 13-Mar-24 16:26:18 UTC` by Gov4Git `dev`

Issued `5000` credits to member @bioregionaltracy.
