### ISSUE TITLE
Issuing tokens to Omo

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#556]
Issue 20000 to @Omoaholo.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 13-Mar-24 22:15:08 UTC` by Gov4Git `dev`

Your directive cannot be parsed.
