### ISSUE TITLE
Comment on Introduction

### ISSUE THREAD

**Issue by vbuterin** [pluralitybook/plurality#58]
> The dominant trends in technology in recent decades have been artificial intelligence and blockchains

I think at the very least social media deserves to be in here as well; it has been just as influential over the relevant time period.

This is particularly interesting because you could construe social media as being "a not very good implementation of DD", so we actually get three things that can be construed as (so far) not very good implementations of all three of "the big 21st-century ideologies".

Though I'd be curious to hear if you @audreyt @glen or anyone else has a different frame on how to think about social media in this context!

**Comment by pluralitybook** [comment]
Great point!  But do see The Lost Dao chapter that gets more into this.  After you read this, give us your perspective on what belongs where and I'm very open to editing.
