### ISSUE TITLE
Images fail to show in Mandarin version in chapter 2 on the website

### ISSUE THREAD

**Issue by mickm3n** [pluralitybook/plurality#61]
https://www.plurality.net/v/chapters/02/zh-tw/

<img width="494" alt="image" src="https://github.com/pluralitybook/plurality/assets/3379504/a0649610-f407-4b68-9886-becd5a043da9">

It's caused by the way to link the picture: [link](https://github.com/pluralitybook/plurality/blob/main/%E7%AC%AC%E4%BA%8C%E7%AB%A0%20%E8%B3%87%E8%A8%8A%E6%8A%80%E8%A1%93%E8%88%87%E6%B0%91%E4%B8%BB%EF%BC%9A%E6%97%A5%E7%9B%8A%E6%93%B4%E5%A4%A7%E7%9A%84%E9%B4%BB%E6%BA%9D.md?plain=1#L141-L142); correct way: [link](https://github.com/pluralitybook/plurality/blob/main/%E7%AC%AC%E4%B8%89%E7%AB%A0%20%E6%B4%BB%E5%9C%A8%E5%A4%9A%E5%85%83%E4%B8%96%E7%95%8C.md?plain=1#L103)

**Comment by GregCTWang** [comment]
Hello @mickm3n , thank you for bringing this up. We are aware of the issue and are working to find a solution. Your input is much appreciated! Thanks again!

**Comment by mickm3n** [comment]
fixed in #68
