### ISSUE TITLE
Issue credits to Greg

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#631]
Issue 20000 credits to @GregCTWang.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Sunday, 17-Mar-24 02:25:03 UTC` by Gov4Git `dev`

Issued `20000` credits to member @gregctwang.
