### ISSUE TITLE
Issuing credit to Nishio

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#684]
Issue 30000 to @nishio.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 18-Mar-24 09:55:08 UTC` by Gov4Git `dev`

Your directive cannot be parsed.
