### ISSUE TITLE
sentences that dont make sense in 7-0

### ISSUE THREAD

**Issue by gnomevan** [pluralitybook/plurality#686]
76: "(d)ecisions about...technology must be made not only 'in the public interest' but in the interest of giving the public itself the means to enter into the decision-making processes that will shape their future.' 

157: Instead it must be ⿻ itself both in its structure and in its connection to existing fora for digital governance the commitments of ⿻ to uplift diversity and collective cooperation.

**Comment by mmiah0** [comment]
76: Removing "(d)ecisions about... from that sentence makes sense. The sentence would then read as follows -
Yet Lick clearly saw that this could not ground the legitimacy of his project for long; as we highlighted central to his aspirations was that technology must be made not only 'in the public interest' but in the interest of giving the public itself the means to enter into the decision-making processes that will shape their future.

157: adding 'of' after governance makes sense.

**Comment by gnomevan** [comment]
nice, those both make more sense. The use of the word fora (which i had to look up to find out is the plural of forum) is a little confusing in this instance, but it does work.

**Comment by GlenWeyl** [comment]
Thanks!

**Comment by GlenWeyl** [comment]
@mmiah0, please enroll in Gov4Git so I can credit you; instructions are linked in the issue template to join and are in the docs folder.
