### ISSUE TITLE
Proposal: Creation of a German-translation Repository

### ISSUE THREAD

**Issue by erichfi** [pluralitybook/plurality#71]
**Summary:** Andreas and I are keen to progress the German translation for the Plurality project. Building upon our previous discussions, here's our roadmap and request:

**1. Repository Setup**
- Request: Create a "German-translation" repository under the @pluralitybook Github account.
- Reason: Hosting under the @pluralitybook Github account will give the translation effort more authenticity and prominence in the community. This centralized location will serve as our primary hub for the translation work.

**2. Onboarding Phase**
- Aim: Onboard our translation contributors in August.
- Activities: Set expectations, distribute tasks, and establish initial milestones.

**3. Execution Phase**
Goal: Sync our translation completion with at least the current English version by year-end.

**4. Community Building**
Plan: Organize community sessions in Germany for engagement and alignment.

**5. Maintenance and Oversight**
- Maintainers: Andreas (@XQTstrategy) and I (@erichfi).
- Role: Ensure efficient translation reviews, updates, and overall quality control.

**Next Steps:**
As we get the repo set up, Andreas and I will be hands-on with community building. We’re also keen on ensuring we can publish translations seamlessly. Looking forward to your thoughts.

**Comment by pluralitybook** [comment]
This sounds great to me!  Make sure to coordinate with @taipeicityeth, who is coordinating all translation forks.

**Comment by XQTStrategy** [comment]
Hi @taipeicityeth, how can we create the German Repository?

**Comment by taipeicityeth** [comment]
hey guys! apologies that didn't see this til now, 

please join our newly spun-up Discord server here: 

https://discord.com/channels/1133444567031627846/1143668522094964806

here's an onboarding flow we created: 

https://taipeicityeth.notion.site/Plurality-Translation-Contributor-Onboarding-8b21ee9cebab42b8b89f8f6a897f849a?pvs=4

one difference I see here compared to what's proposed here is creating the translation repository under the plurality-book account vs forked by the point of contact for each community, let's discuss further what's preferred in the Discord?

Would you guys also be interested in building the German community in the official plurality Discord? could be a great place for translations to stay up to date with each other and for different communities to engage with each other as well

hope to chat soon in Discord, cheers!

**Comment by taipeicityeth** [comment]
hey @XQTStrategy, @erichfi, following up here to see how things are going. Were you guys able to create a fork? or do you still prefer it the fork under the @pluralitybook account? let us know how we can help get you guys going, and what you think of the above

best,
Jacky

**Comment by taipeicityeth** [comment]
That sounds great! Looking forward, please let us know when you have it set up or have other questions, cheers!

**Comment by taipeicityeth** [comment]
hey @XQTStrategy @erichfi, following up here on how things are going, any luck with setting up the repository? anything we could help with?

**Comment by taipeicityeth** [comment]
Hey all, @XQTStrategy @erichfi just wanna follow up here, the Japanese and Ukrainian translation forks are set up in case a reference would be helpful to you guys!

- Ukrainian: https://github.com/vlree-alt/plurality-ukrainian
- Japanese: https://github.com/nishio/plurality-japanese
