### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by hangleang** [pluralitybook/plurality#727]
### Your public repo

https://github.com/hangleang/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Have you contributed to the project yet?

**Comment by hangleang** [comment]
Hi Glen, 

Currently, I haven’t yet. I just found interest in the project, would like to learn more, and get involved. Looking to contribute as much as I can, any areas can I look into?

I will close for now if at any point I can put more efforts, and have to access platform, I will request the permission again.

**Comment by GlenWeyl** [comment]
Thank you so much for your interest.  I suggest you begin by

  1.
Joining Discord at this link: https://discord.gg/d7y92wvX
  2.
Checking out the issue list, with speical attention to the isseus that already have bounties to be addressed (those labeled gov4git:pmp-v1).


___________________________________________________

Research Lead, Plural Technology Collaboratory<https://aka.ms/plural>, Research Special Projects

___________________________________________________

Collaborate<https://github.com/pluralitybook/plurality> with Digital Minister Audrey Tang, myself and dozens around the world to tell the story of Plurality<https://www.plurality.net/>



________________________________

**Comment by hangleang** [comment]
Thanks for the suggestions, I've joined the discord, will check those issues out

closed for now

**Comment by GlenWeyl** [comment]
I don't see you on Discord yet...

**Comment by hangleang** [comment]
I did, just because I'm not using my actual profile. I will chat there

**Comment by hangleang** [comment]
I did, just because I'm not using my actual profile. I will chat there
