### ISSUE TITLE
Proposal: Adding psychological aspect to technology's attack on democracy

### ISSUE THREAD

**Issue by viviantp6** [pluralitybook/plurality#79]
Though the existential and social aspects already covered how the sophistication of technologies has caused fragmentation of social sensemaking and increasing control by authoritarian regimes and centralized cooperations, it did not bring out the "human nature" of the problem. The world is broken, but people would be more willing to fix it if it's related to them. The issue of people's lack of action in fighting the threats against their rights lies in Irrelevance.

Information technology increases the connectivity of the globe, meaning that every single person is exposed to a more complex world than before.  At the same time, the development of all advanced technologies seems way too sophisticated for each individual to understand. The knowledge of the intersecting complexity of both globalization and technological development can't seem to make sense to most human beings. How the world works became irrelevant, and hence the ignorance.

See "21 Lessons for the 21st Century" by Yuval Noah Harari, chapter one - Disillusionment.

**Comment by pluralitybook** [comment]
Conceptually, I definitely like this idea.  I would want it to be grounded in expertise and where possible research to the same extent as the rest fo the chapter, but I support someone taking a swipe at that!

 

From: Vivian ***@***.***> 
Sent: Monday, August 21, 2023 8:57 PM
To: pluralitybook/plurality ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pluralitybook/plurality] Proposal: Adding psychological aspect to technology's attack on democracy (Issue #79)

 

Though the existential and social aspects already covered how the sophistication of technologies has caused fragmentation of social sensemaking and increasing control by authoritarian regimes and centralized cooperations, it did not bring out the "human nature" of the problem. The world is broken, but people would be more willing to fix it if it's related to them. The issue of people's lack of action in fighting the threats against their rights lies in Irrelevance.

Information technology increases the connectivity of the globe, meaning that every single person is exposed to a more complex world than before. At the same time, the development of all advanced technologies seems way too sophisticated for each individual to understand. The knowledge of the intersecting complexity of both globalization and technological development can't seem to make sense to most human beings. How the world works became irrelevant, and hence the ignorance.

See "21 Lessons for the 21st Century" by Yuval Noah Harari, chapter one - Disillusionment.

**Comment by viviantp6** [comment]
Happy to try to look for more references and research that support this argument :)

**Comment by pluralitybook** [comment]
It will also be important to ensure that whatever is highlighted fits in with the rest of the tone and argument of the book and will be addressed by the directions offered in the rest of the book.  I am excited to see what you come up with!

**Comment by GlenWeyl** [comment]
If you still want to do this, only a few weeks left.
