### ISSUE TITLE
I wonder if the book would benefit from some reorganization of the content

### ISSUE THREAD

**Issue by vbuterin** [pluralitybook/plurality#80]
Currently, it feels like the reader is being given a few different narratives:

* There are three modern ideologies: abundance technocracy (AT), entrepreneurial sovereignty (ES), and some mysterious third thing. AT and ES both have big problems, that often go in opposite directions, but in any case both are oversimplifying and do not account for many important aspects of the world. The mysterious third thing, Plurality, does, and here is a big cross-disciplinary description of what the deep underlying philosophy of Plurality is.
* Originally, we had kinship networks. Then, kinship networks were to a large extent replaced by formalized mechanisms, which were good and often liberating, but had their own problems. Now, we're going to formalize plural mechanisms, which have some of the benefits of both.
* There's a century-long strand of research in social science that emphasizes this idea of pluralistic democracy, that then merges into some early internet thinking. However, because of some unfortunate historical accidents, the role of that thinking in ongoing design of the internet stack fell away, and we got a corporate-dominated internet instead.

It feels like these narratives are being presented somewhat haphazardly, without a framework that unifies them. Time in the book jumps around, from the 2010s to the Black Death and back. Of course, it is part of the spirit of Plurality that there are multiple narratives :) But I feel like a better job could be done of gluing them together, and presenting them as different aspects of what is ultimately the same issue.

I'm not sure exactly what is the best way to do this. I have a feeling that it involves a pretty large reorganization of some of the content. For example, here's one possible reordering:

1. The first ~half of the "Introduction" chapter: specifically the two sections "Technology’s Attack on Democracy" and "Democracies’ Hostility to Technology", but not anything further from that chapter yet. This does a good job of setting up for the reader what is the problem that the book tries to address.
2. The Lost Dao chapter, with the introduction reworked a bit. This does a good job of giving the authors' vision of what the "institutional and intellectual history of the world" has been. Probably don't include the "Nodes of light" section yet
3. The rest of the Introduction. Probably call this chapter "Ideologies of the present". Bring back the discussion of AT and ES, and then suggest that there is a third thing. Maybe use the "Nodes of light" section as a way of giving the reader examples as a hint of what this third thing is like.
4. The "Plural World" chapter. Go deep on the philosophy of Plurality.
5. Go deep on Estonia and Taiwan and other examples, describing them as examples of a proto- version of Plurality in practice, and successes to be built upon. Talk about what is still missing.

This would present the same content in a way that feels to me like it gives the reader a more coherent narrative, though one that can and should be approached from multiple historical and intellectual angles.

**Comment by pluralitybook** [comment]
@vbuterin, these are really great thoughts.  I think I'd like to collect some more feedback from others, ensure we have the full Plurality section (including the chapter @audreyt is leading on about Taiwan) and maybe a bit more of the book and talk this over with @audreyt before we make any structural changes like this...but I share your concerns and once we have these things in place would welcome your taking a swipe at this if it makes sense.
