### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by AngryAngryMouse** [pluralitybook/plurality#850]
### Your public repo

https://github.com/angryangrymouse/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Have you yet contributed to the project?

**Comment by AngryAngryMouse** [comment]
Hi Glen, This is Richard. Maybe I should have chosen handle RichardGarfield rather than AngryAngryMouse.





________________________________

**Comment by GlenWeyl** [comment]
Approved

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Sunday, 07-Apr-24 17:09:08 UTC` by Gov4Git `dev`

@angryangrymouse was added to the community.
