### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by andreabonac** [pluralitybook/plurality#875]
### Your public repo

https://github.com/andreabonac/gov4git-identity-public.git

### Your public branch

main

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Thursday, 11-Apr-24 20:45:12 UTC` by Gov4Git `dev`

@andreabonac was added to the community.
