### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by byteofpython** [pluralitybook/plurality#902]
### Your public repo

https://github.com/byteofpython/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Hi who is this and what have you thus far contributed to the community?

**Comment by byteofpython** [comment]
Hi, my name is Ferdinand, I was at your talk last week in Brussels and wanted to contribute somehow - possibly on the German translation but I have not contributed yet as I am still trying to figure things out.

**Comment by GlenWeyl** [comment]
Great thanks for coming onto Discord let's figure it out there.

**Comment by GlenWeyl** [comment]
Approved.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Saturday, 04-May-24 16:11:49 UTC` by Gov4Git `dev`

@byteofpython was added to the community.
