### ISSUE TITLE
Issue credits to Gisele

### ISSUE THREAD

**Issue by GlenWeyl** [pluralitybook/plurality#922]
Issue 100000 credits to @giselechou.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 20-May-24 15:09:01 UTC` by Gov4Git `dev`

Issued `100000` credits to member @giselechou.
