### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by JeviNifer** [pluralitybook/plurality#927]
### Your public repo

https://github.com/jevinifer/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Have you contributed to the project yet?

**Comment by JeviNifer** [comment]
Hi Glen, I have not yet git pushed the chapters I translated into Germen (chapters 0, 1, 5, 7).

**Comment by GlenWeyl** [comment]
Didn't realize it was you!

**Comment by GlenWeyl** [comment]
Approved

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Wednesday, 29-May-24 03:42:11 UTC` by Gov4Git `dev`

@jevinifer was added to the community.
