### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by hqueue** [pluralitybook/plurality#933]
### Your public repo

https://github.com/hqueue/gov4git-identity-public.git

### Your public branch

main

**Comment by hqueue** [comment]
I was invited by a tweet reply at https://x.com/pluralitybook/status/1795925410250670241

**Comment by GlenWeyl** [comment]
Accepted

**Comment by GlenWeyl** [comment]
Approved

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Thursday, 30-May-24 11:39:12 UTC` by Gov4Git `dev`

@hqueue was added to the community.
