### ISSUE TITLE
How to build releases and how to edit the book?

### ISSUE THREAD

**Issue by DashBing** [pluralitybook/plurality#964]
What toolchain do you use to edit these files?

**Comment by DashBing** [comment]
I'd like to contribute but I obviously have no idea what tool this was written in

**Comment by josephtownshend** [comment]
It's written in mark down using Jupyter Notebook. Install Git on your machine, then clone the repo. You'll then need to make a branch, make your changes and then submit a pull request. Someone will review your changes and merge your pull request. Hope this helps.

**Comment by josephtownshend** [comment]
I'd like to bump this issue - there should be a contributing.md that shows you how to actually contribute to this repo. With a clear set of instructions for how to set it up. 

I'm happy to create that, if others agree?

**Comment by chusanap** [comment]
[Beginners contribution guide](https://docs.plurality.net/contributing/Beginners%20contribution%20guide/)

**Comment by josephtownshend** [comment]
thats great, it needs to be linked in the read me though. unless Im missing it?

**Comment by chusanap** [comment]
[Beginners contribution guide.md](https://github.com/pluralitybook/plurality/blob/main/docs/contributing/Beginners%20contribution%20guide.md)

I think this is what you were referring to? Apology if I'm mistaken.

**Comment by josephtownshend** [comment]
ah its hidden away.
