### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by tommiiik** [pluralitybook/plurality#968]
### Your public repo

https://github.com/tommiiik/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Have you yet contributed to the project?

**Comment by tommiiik** [comment]
I've translated into Italian the updated Annoucement (it was a couple of years old) and I'm onto the translation of the book.

**Comment by GlenWeyl** [comment]
Approved.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 12-Aug-24 06:31:12 UTC` by Gov4Git `dev`

@tommiiik was added to the community.
