### ISSUE TITLE
I'd like to join this project's community

### ISSUE THREAD

**Issue by engn33r** [pluralitybook/plurality#973]
### Your public repo

https://github.com/engn33r/gov4git-identity-public.git

### Your public branch

main

**Comment by GlenWeyl** [comment]
Have you contributed yet to the project?

**Comment by engn33r** [comment]
Yes, with https://github.com/pluralitybook/plurality/pull/965

**Comment by GlenWeyl** [comment]
Approved.

**Comment by pluralitybook-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 12-Aug-24 06:00:32 UTC` by Gov4Git `dev`

@engn33r was added to the community.
